--
-- star-fusion 1.15.1 modulefile
--

whatis("Name: STAR-Fusion")
whatis("Version: 1.15.1")
whatis("Category: Biological Sciences")
whatis("URL: https://github.com/STAR-Fusion/STAR-Fusion")
whatis("Description: STAR-Fusion is a component of the Trinity Cancer Transcriptome Analysis Toolkit (CTAT). STAR-Fusion uses the STAR aligner to identify candidate fusion transcripts supported by Illumina reads. STAR-Fusion further processes the output generated by the STAR aligner to map junction reads and spanning reads to a reference annotation set.")
whatis("Keywords: singularity bioinformatics fusion rna-seq")

family("star-fusion")

help([[
STAR-Fusion is a component of the Trinity Cancer Transcriptome Analysis Toolkit (CTAT). STAR-Fusion uses the STAR aligner to identify candidate fusion transcripts supported by Illumina reads. STAR-Fusion further processes the output generated by the STAR aligner to map junction reads and spanning reads to a reference annotation set.
Runs inside a Singularity container.

To load the module type

  > module load star-fusion/1.15.1

To unload the module type

  > module unload star-fusion/1.15.1

Documentation
-------------
For help, type

  > STAR-Fusion --help

Upstream repository: https://github.com/STAR-Fusion/STAR-Fusion

Tools
-----
* STAR-Fusion
* FusionInspector
* FusionAnnotator
* blast_and_promiscuity_filter.pl
]])

local package  = "star-fusion"
local version  = "1.15.1"
local root     = os.getenv("CONTAINERS_ROOT") or "/shared/containers"
local base     = pathJoin(root, package, version)

conflict("star-fusion")
prepend_path("PATH", base)
setenv("STAR_FUSION_SIF", pathJoin(base, "singularity-" .. package .. "-" .. version .. ".sif"))
