#!/bin/bash

# Copyright © 2026 Pittsburgh Supercomputing Center.
# All Rights Reserved.

VERSION=1.15.1
PACKAGE=star-fusion
TOOL=STAR-Fusion
DIRECTORY=$(dirname $0)

if [ -f /shared/containers/loader ]; then
  source /shared/containers/loader
fi

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
