#!/bin/bash

VERSION=1.15.1
PACKAGE=star-fusion
TOOL=STAR-Fusion
DIRECTORY=$(dirname $0)

if [ -f /containers/loader ]; then
  source /containers/loader
fi

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
